name: Build and Push Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} #dapet dari apikey docker trus disetup digithub 
        password: ${{ secrets.DOCKER_PASSWORD }} #dapet dari apikey docker trus disetup digithub;
    
    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: 
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/movie:development